import type { SolarSLDProject } from '../types/solar';
import { STANDARD_ENGINEERS } from './equipment';

export const DEFAULT_PRESETS: SolarSLDProject[] = [
  // Preset 1: Enphase 1-Phase (5.715 kWp, 9 Panels x 635W, 9 IQ7A) - Matching Sample 1
  {
    id: 'enphase-1p-5.7kw',
    title: 'Enphase 1-Phase (5.715 kWp - 9 Panels IQ7A)',
    paperSize: 'A3',
    orientation: 'landscape',
    showRelayTable: false,
    showZeroExportNote: true,
    showPhaseProtectionNote: true,
    projectInfo: {
      projectOwner: 'TNS Network Solutions Co.,Ltd.',
      projectName: 'Solar Rooftop',
      customerName: 'คุณ นิติศักดิ์ โพธิ์หน่อทอง',
      location: '10/13 ม. 6 ต.บ้านสวน อ.เมืองชลบุรี จ.ชลบุรี 20000',
      coordinates: '13.33764° N, 100.93830° E',
      jobNo: '020028212022',
      drawingNo: 'SLD-01',
      revision: 'Rev. 00001',
      date: '24 JUN 2026',
      engineer: STANDARD_ENGINEERS[0],
      gridAuthority: 'PEA',
      gridVoltage: '220 V',
      gridCableSpec: '2x1C-16 sq.mm. IEC01 In Aerial',
    },
    pvConfig: {
      brand: 'LONGi',
      model: 'LR5-78HGD-635M',
      powerPerPanel: 635,
      panelCount: 9,
      voc: 57.39,
      isc: 13.97,
      vmp: 48.15,
      imp: 13.19,
      totalKwp: 5.715,
    },
    inverterConfig: {
      systemType: 'microinverter',
      brand: 'Enphase',
      model: 'IQ7A-72-2-INT',
      phase: '1P',
      microinverterCount: 9,
      unitPowerKw: 0.349,
      unitPowerVa: 366,
      unitMaxCurrent: 1.52,
      stringInverterCapacityKw: 3.3,
      stringInverterQuantity: 1,
      stringCount: 1,
      modulesPerString: 9,
      mpptCount: 1,
      totalOutputKw: 3.294,
      totalOutputKva: 3.294,
      hasAntiIslanding: true,
      hasRapidShutdown: true,
    },
    combinerConfig: {
      rcboRating: '20AT 2P',
      rcboType: 'IΔn<30mA ,IC 6kA Type AC',
      mcbRating: 'MCB 2P 20AT,63AF IC 6kA',
      mccbRating: 'MCCB 2P 20AT 63AF',
      acSpdRating: 'AC SPD 2P TYPE II 5/20 KA ~255VAC',
      gatewayModel: 'Meter Envoy-S-ENV-S-WM-230',
      productionCt: 'CTs 200A/40mA',
      consumptionCt: 'CT 200A/40mA',
      phaseCoupler: '',
      hasZeroExport: true,
      hasPhaseCoupler: false,
      cableInverterToCombiner: '1x2C-4 Sq.mm.IEC 60502-1 (CV-FR) / G 6 Sq.mm. IEC01 in PVC 1"',
      cableCombinerToMdb: '2x1C-6 Sq.mm.IEC01 / G6 Sq.mm. IEC01 IN WIREWAY',
      groundRodSpec: '5/8"x10\' COPPER CLAD STEEL GROUND ROD ความต้านทานดินไม่เกิน 5 โอห์ม',
      groundCableSpec: 'G - 10 Sq.mm. IEC 01 (THW)',
    },
    loadCenterConfig: {
      title: 'Consumer Unit',
      mainBreaker: 'RCBO 50AT, 2P IC 10kA IΔn<30mA Type AC',
      solarFeederBreaker: 'MCB 2P 20 AT IC 6kA',
      busbarSpec: 'BUSBAR 100A 100%N & 25% GROUND BUSBAR',
      groundRodSpec: '5/8"x10\' COPPER CLAD STEEL GROUND ROD ความต้านทานดินไม่เกิน 5 โอห์ม',
    },
  },

  // Preset 2: Enphase 3-Phase 10.08 kVA / 13.545 kWp (21 Panels x 645W, 21 IQ8P) - Matching Sample 2
  {
    id: 'enphase-3p-13.5kw',
    title: 'Enphase 3-Phase (13.545 kWp - 21 Panels IQ8P)',
    paperSize: 'A3',
    orientation: 'landscape',
    showRelayTable: false,
    showZeroExportNote: true,
    showPhaseProtectionNote: true,
    projectInfo: {
      projectOwner: 'TNS Network Solutions Co.,Ltd.',
      projectName: 'Solar Rooftop ร้านเชียงใหม่พลาสติก',
      customerName: 'บริษัท เชียงใหม่พลาสติก จำกัด',
      location: '68 ถ.ชวงมรุ ต.ช้างม่อย อ.เมืองเชียงใหม่ จ.เชียงใหม่ 50300',
      coordinates: '18.78925° N, 99.00050° E',
      jobNo: '20005251925',
      drawingNo: 'SLD-01',
      revision: 'Rev. 00001',
      date: '24 JUN 2026',
      engineer: STANDARD_ENGINEERS[0],
      gridAuthority: 'PEA',
      gridVoltage: '380 / 220 V',
      gridCableSpec: '1x4Cx35 sq.mm. IEC01 IN AERIAL',
    },
    pvConfig: {
      brand: 'LONGi',
      model: 'LR7-72HVH-645M',
      powerPerPanel: 645,
      panelCount: 21,
      voc: 53.80,
      isc: 15.21,
      vmp: 44.46,
      imp: 14.51,
      totalKwp: 13.545,
    },
    inverterConfig: {
      systemType: 'microinverter',
      brand: 'Enphase',
      model: 'IQ8P-72-2-INT',
      phase: '3P',
      microinverterCount: 21,
      unitPowerKw: 0.475,
      unitPowerVa: 480,
      unitMaxCurrent: 2.07,
      stringInverterCapacityKw: 10,
      stringInverterQuantity: 1,
      stringCount: 1,
      modulesPerString: 21,
      mpptCount: 1,
      totalOutputKw: 9.975,
      totalOutputKva: 10.08,
      hasAntiIslanding: true,
      hasRapidShutdown: true,
    },
    combinerConfig: {
      rcboRating: 'RCBO 4P 40AT',
      rcboType: 'IΔn<30mA Type AC',
      mcbRating: 'MCB 3P 20AT 63AF Ic 6kA',
      mccbRating: 'MCCB 3P 20AT 100AF Ic 10kA',
      acSpdRating: 'AC SPD 4P TYPE II 20/40 KA ~385VAC',
      gatewayModel: 'Meter Envoy-S-ENV-S-WM-230',
      productionCt: '3 x CTs 100A / 40mA',
      consumptionCt: '3 x CTs 100A / 40mA',
      phaseCoupler: 'Legrand Phase Coupler',
      hasZeroExport: true,
      hasPhaseCoupler: true,
      cableInverterToCombiner: '1x4C-10 sq.mm. CV-FD / G 6 sq.mm. IEC01 IN 1" IMC',
      cableCombinerToMdb: '4x1C-10 sq.mm. / G 6 sq.mm. IEC01 IN 1 1/2" IMC',
      groundRodSpec: '5/8"x10\' COPPER CLAD STEEL GROUND ROD ความต้านทานดินไม่เกิน 5 โอห์ม',
      groundCableSpec: '1x16 sq.mm. /IEC01 (G)',
    },
    loadCenterConfig: {
      title: 'Consumer Unit / Load Center',
      mainBreaker: 'MCCB 3P 50AT 100AF Ic 10kA',
      solarFeederBreaker: 'MCB 3P 20AT 63AF',
      busbarSpec: 'BUSBAR 100A 100%N & 25% GROUND BUSBAR',
      groundRodSpec: '5/8"x10\' COPPER CLAD STEEL GROUND ROD ความต้านทานดินไม่เกิน 5 โอห์ม',
    },
  },

  // Preset 3: Enphase 3-Phase (5.235 kW / 9.45 kWp - 15 Panels IQ7A) - Matching Sample 3
  {
    id: 'enphase-3p-9.45kw',
    title: 'Enphase 3-Phase (9.45 kWp - 15 Panels IQ7A)',
    paperSize: 'A3',
    orientation: 'landscape',
    showRelayTable: false,
    showZeroExportNote: true,
    showPhaseProtectionNote: true,
    projectInfo: {
      projectOwner: 'TNS Network Solutions Co.,Ltd.',
      projectName: 'Solar Cell Rooftop Enphase MicroInverter IQ7A -15PVs-630Wp Three-Phase',
      customerName: 'ประมุก โรจนาประดับ',
      location: '62/218 โครงการตำนานลานนาควิล ม.5 ต.ตลาดขวัญ อ.ดอยสะเก็ด จ.เชียงใหม่ 50220',
      coordinates: '18.83394N , 99.09307E',
      jobNo: '2608 PSLC-230821-01',
      drawingNo: 'PSLC-2608',
      revision: 'rev. 00001',
      date: '7 MAR 2025',
      engineer: STANDARD_ENGINEERS[1],
      gridAuthority: 'PEA',
      gridVoltage: '380 / 220 V',
      gridCableSpec: '1x4Cx16 sq.mm. CV IN HDPE -Underground',
    },
    pvConfig: {
      brand: 'LONGi',
      model: 'LR5-78HDG-630M',
      powerPerPanel: 630,
      panelCount: 15,
      voc: 57.23,
      isc: 13.91,
      vmp: 47.99,
      imp: 13.13,
      totalKwp: 9.45,
    },
    inverterConfig: {
      systemType: 'microinverter',
      brand: 'Enphase',
      model: 'IQ7A-72-2-INT',
      phase: '3P',
      microinverterCount: 15,
      unitPowerKw: 0.349,
      unitPowerVa: 366,
      unitMaxCurrent: 1.49,
      stringInverterCapacityKw: 5,
      stringInverterQuantity: 1,
      stringCount: 1,
      modulesPerString: 15,
      mpptCount: 1,
      totalOutputKw: 5.235,
      totalOutputKva: 5.49,
      hasAntiIslanding: true,
      hasRapidShutdown: true,
    },
    combinerConfig: {
      rcboRating: 'RCBO 4P 32AT 63AF',
      rcboType: 'Type AC 30mA',
      mcbRating: 'MCB 3P 10AT 63AF',
      mccbRating: 'MCCB 3P 20AT 100AF',
      acSpdRating: 'AC SPD TYPE II 20/40 KA ~385VAC',
      gatewayModel: 'Meter Envoy-S-ENV-S-WM-230',
      productionCt: '3 x CTs 100A / 40mA',
      consumptionCt: '3 x CTs 100A / 40mA',
      phaseCoupler: 'Legrand Phase Coupler',
      hasZeroExport: true,
      hasPhaseCoupler: true,
      cableInverterToCombiner: '1x4C-4 sq.mm. CV-FD / G 6 sq.mm. IEC01 IN PVC 1"',
      cableCombinerToMdb: '4x6 sq.mm. / G 6 sq.mm. IEC01 IN PVC 1"',
      groundRodSpec: '5/8" x 2.4 m ความต้านทานดินไม่เกิน 5 โอห์ม',
      groundCableSpec: '1x10 sq.mm. /IEC01 (G)',
    },
    loadCenterConfig: {
      title: 'LOAD CENTER',
      mainBreaker: 'MCCB 3P 50AT 100AF',
      solarFeederBreaker: 'MCB 3P 20AT 63AF',
      busbarSpec: 'BUSBAR 100A 100%N & 25% GROUND BUSBAR',
      groundRodSpec: 'Ground rod 5/8" x 2.4 m',
    },
  },

  // Preset 4: User requested system - 5kW Microinverter (8 Panels x 650W)
  {
    id: 'enphase-1p-5kw-8panels',
    title: 'Enphase 1-Phase 5kW (8 Panels x 650W = 5.20 kWp)',
    paperSize: 'A3',
    orientation: 'landscape',
    showRelayTable: false,
    showZeroExportNote: true,
    showPhaseProtectionNote: true,
    projectInfo: {
      projectOwner: 'TNS Network Solutions Co.,Ltd.',
      projectName: 'Solar Rooftop 5kW 1-Phase',
      customerName: 'คุณสมชาย ใจดี',
      location: '123 หมู่ 2 ต.สุเทพ อ.เมือง จ.เชียงใหม่ 50200',
      coordinates: '18.790382, 98.956784',
      jobNo: '02002601001',
      drawingNo: 'SLD-01',
      revision: 'Rev. 00001',
      date: '17 AUG 2026',
      engineer: STANDARD_ENGINEERS[0],
      gridAuthority: 'PEA',
      gridVoltage: '220 V',
      gridCableSpec: '2x1C-16 sq.mm. IEC01 In Aerial',
    },
    pvConfig: {
      brand: 'LONGi',
      model: 'LR5-78HGD-650M',
      powerPerPanel: 650,
      panelCount: 8,
      voc: 57.80,
      isc: 14.15,
      vmp: 48.50,
      imp: 13.40,
      totalKwp: 5.20,
    },
    inverterConfig: {
      systemType: 'microinverter',
      brand: 'Enphase',
      model: 'IQ8P-72-2-INT',
      phase: '1P',
      microinverterCount: 8,
      unitPowerKw: 0.475,
      unitPowerVa: 480,
      unitMaxCurrent: 2.07,
      stringInverterCapacityKw: 5,
      stringInverterQuantity: 1,
      stringCount: 1,
      modulesPerString: 8,
      mpptCount: 1,
      totalOutputKw: 3.80,
      totalOutputKva: 3.84,
      hasAntiIslanding: true,
      hasRapidShutdown: true,
    },
    combinerConfig: {
      rcboRating: '20AT 2P',
      rcboType: 'IΔn<30mA ,IC 6kA Type AC',
      mcbRating: 'MCB 2P 20AT,63AF IC 6kA',
      mccbRating: 'MCCB 2P 20AT 63AF',
      acSpdRating: 'AC SPD 2P TYPE II 5/20 KA ~255VAC',
      gatewayModel: 'Meter Envoy-S-ENV-S-WM-230',
      productionCt: 'CTs 200A/40mA',
      consumptionCt: 'CT 200A/40mA',
      phaseCoupler: '',
      hasZeroExport: true,
      hasPhaseCoupler: false,
      cableInverterToCombiner: '1x2C-4 Sq.mm.IEC 60502-1 (CV-FR) / G 6 Sq.mm. IEC01 in PVC 1"',
      cableCombinerToMdb: '2x1C-6 Sq.mm.IEC01 / G6 Sq.mm. IEC01 IN WIREWAY',
      groundRodSpec: '5/8"x10\' COPPER CLAD STEEL GROUND ROD ความต้านทานดินไม่เกิน 5 โอห์ม',
      groundCableSpec: 'G - 10 Sq.mm. IEC 01 (THW)',
    },
    loadCenterConfig: {
      title: 'Consumer Unit',
      mainBreaker: 'RCBO 50AT, 2P IC 10kA IΔn<30mA Type AC',
      solarFeederBreaker: 'MCB 2P 20 AT IC 6kA',
      busbarSpec: 'BUSBAR 100A 100%N & 25% GROUND BUSBAR',
      groundRodSpec: '5/8"x10\' COPPER CLAD STEEL GROUND ROD ความต้านทานดินไม่เกิน 5 โอห์ม',
    },
  },

  // Preset 5: User requested system - Huawei 5kW 3-Phase (8 Panels x 650W = 5.20 kWp)
  {
    id: 'huawei-3p-5kw-8panels',
    title: 'Huawei 3-Phase 5kW (8 Panels x 650W = 5.20 kWp)',
    paperSize: 'A3',
    orientation: 'landscape',
    showRelayTable: true,
    showZeroExportNote: true,
    showPhaseProtectionNote: true,
    projectInfo: {
      projectOwner: 'TNS Network Solutions Co.,Ltd.',
      projectName: 'Solar Rooftop Huawei SUN2000-5KTL-M1 (3-Phase)',
      customerName: 'คุณประสิทธิ์ พัฒนา',
      location: '88/9 หมู่ 5 ต.หนองป่าครั่ง อ.เมืองเชียงใหม่ จ.เชียงใหม่ 50000',
      coordinates: '18.791520, 99.023450',
      jobNo: '02002601002',
      drawingNo: 'SLD-01',
      revision: 'Rev. 00001',
      date: '17 AUG 2026',
      engineer: STANDARD_ENGINEERS[0],
      gridAuthority: 'PEA',
      gridVoltage: '380 / 220 V',
      gridCableSpec: '1x4Cx16 sq.mm. CV IN HDPE -Underground',
    },
    pvConfig: {
      brand: 'LONGi',
      model: 'LR5-78HGD-650M',
      powerPerPanel: 650,
      panelCount: 8,
      voc: 57.80,
      isc: 14.15,
      vmp: 48.50,
      imp: 13.40,
      totalKwp: 5.20,
    },
    inverterConfig: {
      systemType: 'string_inverter',
      brand: 'Huawei',
      model: 'SUN2000-5KTL-M1',
      phase: '3P',
      microinverterCount: 0,
      unitPowerKw: 5.0,
      unitPowerVa: 5500,
      unitMaxCurrent: 8.5,
      stringInverterCapacityKw: 5,
      stringInverterQuantity: 1,
      stringCount: 1,
      modulesPerString: 8,
      mpptCount: 2,
      totalOutputKw: 5.0,
      totalOutputKva: 5.5,
      hasAntiIslanding: true,
      hasRapidShutdown: true,
    },
    combinerConfig: {
      rcboRating: 'RCBO 4P 20AT',
      rcboType: 'IΔn<30mA Type AC',
      mcbRating: 'MCB 3P 16AT 63AF Ic 6kA',
      mccbRating: 'MCCB 3P 20AT 100AF Ic 10kA',
      acSpdRating: 'AC SPD 4P TYPE II 20/40 KA ~385VAC',
      gatewayModel: 'Smart Power Sensor DTSU666-H (3-Phase)',
      productionCt: '3 x CTs 100A / 40mA',
      consumptionCt: '3 x CTs 100A / 40mA',
      phaseCoupler: '',
      hasZeroExport: true,
      hasPhaseCoupler: false,
      cableInverterToCombiner: '1x4C-4 sq.mm. CV-FD / G 6 sq.mm. IEC01 IN 1" PVC',
      cableCombinerToMdb: '4x6 sq.mm. / G 6 sq.mm. IEC01 IN PVC 1"',
      groundRodSpec: '5/8" x 2.4 m ความต้านทานดินไม่เกิน 5 โอห์ม',
      groundCableSpec: '1x10 sq.mm. /IEC01 (G)',
      dcFuseRating: 'DC FUSE 15A 1000V DC (gPV)',
      dcIsolatorRating: 'DC ISOLATOR SWITCH 1000V DC 25A',
      dcSpdRating: 'DC SPD TYPE II 1000V DC 20/40kA',
      dcCableSpec: '1x2C-4 sq.mm. PV1-F / H1Z2Z2-K (SOLAR CABLE)',
    },
    loadCenterConfig: {
      title: 'LOAD CENTER',
      mainBreaker: 'MCCB 3P 50AT 100AF',
      solarFeederBreaker: 'MCB 3P 16AT 63AF',
      busbarSpec: 'BUSBAR 100A 100%N & 25% GROUND BUSBAR',
      groundRodSpec: 'Ground rod 5/8" x 2.4 m',
    },
  },

  // Preset 6: Huawei 10kW 3-Phase (16 Panels x 650W = 10.4 kWp)
  {
    id: 'huawei-3p-10kw',
    title: 'Huawei 3-Phase 10kW (16 Panels x 650W = 10.40 kWp)',
    paperSize: 'A3',
    orientation: 'landscape',
    showRelayTable: true,
    showZeroExportNote: true,
    showPhaseProtectionNote: true,
    projectInfo: {
      projectOwner: 'TNS Network Solutions Co.,Ltd.',
      projectName: 'Solar Rooftop Huawei SUN2000-10KTL-M2 (3-Phase)',
      customerName: 'หจก. เชียงใหม่ พาณิชย์การ',
      location: '45/1 ถนนช้างคลาน ต.ช้างคลาน อ.เมืองเชียงใหม่ จ.เชียงใหม่ 50100',
      coordinates: '18.775430, 98.998720',
      jobNo: '02002601003',
      drawingNo: 'SLD-01',
      revision: 'Rev. 00001',
      date: '17 AUG 2026',
      engineer: STANDARD_ENGINEERS[0],
      gridAuthority: 'PEA',
      gridVoltage: '380 / 220 V',
      gridCableSpec: '1x4Cx25 sq.mm. CV IN HDPE -Underground',
    },
    pvConfig: {
      brand: 'LONGi',
      model: 'LR5-78HGD-650M',
      powerPerPanel: 650,
      panelCount: 16,
      voc: 57.80,
      isc: 14.15,
      vmp: 48.50,
      imp: 13.40,
      totalKwp: 10.40,
    },
    inverterConfig: {
      systemType: 'string_inverter',
      brand: 'Huawei',
      model: 'SUN2000-10KTL-M2',
      phase: '3P',
      microinverterCount: 0,
      unitPowerKw: 10.0,
      unitPowerVa: 11000,
      unitMaxCurrent: 16.9,
      stringInverterCapacityKw: 10,
      stringInverterQuantity: 1,
      stringCount: 2,
      modulesPerString: 8,
      mpptCount: 2,
      totalOutputKw: 10.0,
      totalOutputKva: 11.0,
      hasAntiIslanding: true,
      hasRapidShutdown: true,
    },
    combinerConfig: {
      rcboRating: 'RCBO 4P 32AT',
      rcboType: 'IΔn<30mA Type AC',
      mcbRating: 'MCB 3P 25AT 63AF Ic 6kA',
      mccbRating: 'MCCB 3P 32AT 100AF Ic 10kA',
      acSpdRating: 'AC SPD 4P TYPE II 20/40 KA ~385VAC',
      gatewayModel: 'Smart Power Sensor DTSU666-H (3-Phase)',
      productionCt: '3 x CTs 100A / 40mA',
      consumptionCt: '3 x CTs 100A / 40mA',
      phaseCoupler: '',
      hasZeroExport: true,
      hasPhaseCoupler: false,
      cableInverterToCombiner: '1x4C-6 sq.mm. CV-FD / G 6 sq.mm. IEC01 IN 1" PVC',
      cableCombinerToMdb: '4x10 sq.mm. / G 10 sq.mm. IEC01 IN 1 1/4" PVC',
      groundRodSpec: '5/8" x 2.4 m ความต้านทานดินไม่เกิน 5 โอห์ม',
      groundCableSpec: '1x10 sq.mm. /IEC01 (G)',
      dcFuseRating: '2 Strings x DC FUSE 15A 1000V DC (gPV)',
      dcIsolatorRating: 'DC ISOLATOR SWITCH 1000V DC 32A',
      dcSpdRating: 'DC SPD TYPE II 1000V DC 20/40kA',
      dcCableSpec: '2 x (1x2C-4 sq.mm. PV1-F / H1Z2Z2-K)',
    },
    loadCenterConfig: {
      title: 'LOAD CENTER',
      mainBreaker: 'MCCB 3P 100AT 100AF',
      solarFeederBreaker: 'MCB 3P 25AT 63AF',
      busbarSpec: 'BUSBAR 160A 100%N & 25% GROUND BUSBAR',
      groundRodSpec: 'Ground rod 5/8" x 2.4 m',
    },
  },

  // Preset 7: Huawei 50kW 3-Phase Commercial
  {
    id: 'huawei-3p-50kw',
    title: 'Huawei 3-Phase 50kW Commercial (80 Panels x 650W = 52.0 kWp)',
    paperSize: 'A3',
    orientation: 'landscape',
    showRelayTable: true,
    showZeroExportNote: true,
    showPhaseProtectionNote: true,
    projectInfo: {
      projectOwner: 'TNS Network Solutions Co.,Ltd.',
      projectName: 'Solar Rooftop Huawei SUN2000-50KTL-M3 (3-Phase)',
      customerName: 'บริษัท เชียงใหม่ อุตสาหกรรม จำกัด',
      location: '199 นิคมอุตสาหกรรมภาคเหนือ ต.บ้านกลาง อ.เมือง จ.ลำพูน 51000',
      coordinates: '18.572110, 99.034510',
      jobNo: '02002601050',
      drawingNo: 'SLD-50K',
      revision: 'Rev. 00001',
      date: '17 AUG 2026',
      engineer: STANDARD_ENGINEERS[0],
      gridAuthority: 'PEA',
      gridVoltage: '380 / 220 V',
      gridCableSpec: '1x4Cx95 sq.mm. XLPE IN HDPE -Underground',
    },
    pvConfig: {
      brand: 'LONGi',
      model: 'LR5-78HGD-650M',
      powerPerPanel: 650,
      panelCount: 80,
      voc: 57.80,
      isc: 14.15,
      vmp: 48.50,
      imp: 13.40,
      totalKwp: 52.0,
    },
    inverterConfig: {
      systemType: 'string_inverter',
      brand: 'Huawei',
      model: 'SUN2000-50KTL-M3',
      phase: '3P',
      microinverterCount: 0,
      unitPowerKw: 50.0,
      unitPowerVa: 55000,
      unitMaxCurrent: 79.7,
      stringInverterCapacityKw: 50,
      stringInverterQuantity: 1,
      stringCount: 4,
      modulesPerString: 20,
      mpptCount: 4,
      totalOutputKw: 50.0,
      totalOutputKva: 55.0,
      hasAntiIslanding: true,
      hasRapidShutdown: true,
    },
    combinerConfig: {
      rcboRating: 'MCCB 3P 100AT + ELR (Earth Leakage Relay)',
      rcboType: 'IΔn<30mA Type AC',
      mcbRating: 'MCCB 3P 100AT 125AF Ic 18kA',
      mccbRating: 'MCCB 3P 100AT 125AF Ic 25kA',
      acSpdRating: 'AC SPD 4P TYPE II 20/40 KA ~385VAC',
      gatewayModel: 'Smart Power Sensor DTSU666-H (3-Phase)',
      productionCt: '3 x CTs 200A / 5A',
      consumptionCt: '3 x CTs 400A / 5A',
      phaseCoupler: '',
      hasZeroExport: true,
      hasPhaseCoupler: false,
      cableInverterToCombiner: '1x4C-35 sq.mm. CV / G 16 sq.mm. IEC01 IN 2" IMC',
      cableCombinerToMdb: '4x35 sq.mm. / G 16 sq.mm. IEC01 IN WIREWAY 200x100mm',
      groundRodSpec: '5/8" x 2.4 m ความต้านทานดินไม่เกิน 5 โอห์ม',
      groundCableSpec: '1x16 sq.mm. /IEC01 (G)',
      dcFuseRating: '4 Strings x DC FUSE 20A 1100V DC (gPV)',
      dcIsolatorRating: 'DC ISOLATOR SWITCH 1100V DC 100A',
      dcSpdRating: 'DC SPD TYPE II 1100V DC 20/40kA',
      dcCableSpec: '4 x (1x2C-4 sq.mm. PV1-F / H1Z2Z2-K)',
    },
    loadCenterConfig: {
      title: 'MAIN DISTRIBUTION BOARD (MDB)',
      mainBreaker: 'MCCB 3P 400AT 400AF Ic 35kA',
      solarFeederBreaker: 'MCCB 3P 100AT 125AF Ic 25kA',
      busbarSpec: 'BUSBAR 500A 100%N & 25% GROUND BUSBAR',
      groundRodSpec: 'Ground rod 5/8" x 2.4 m',
    },
  },

  // Preset 8: ATMOCE Microinverter System (5kW 1-Phase / 3-Phase)
  {
    id: 'atmoce-1p-5kw',
    title: 'ATMOCE Microinverter (5.20 kWp - 8 Panels x 650W)',
    paperSize: 'A3',
    orientation: 'landscape',
    showRelayTable: false,
    showZeroExportNote: true,
    showPhaseProtectionNote: true,
    projectInfo: {
      projectOwner: 'TNS Network Solutions Co.,Ltd.',
      projectName: 'Solar Rooftop ATMOCE Microinverter 5kW',
      customerName: 'คุณกิตติศักดิ์ ศรีวิชัย',
      location: '55/2 ถ.ห้วยแก้ว ต.สุเทพ อ.เมือง จ.เชียงใหม่ 50200',
      coordinates: '18.805210, 98.962140',
      jobNo: '02002601008',
      drawingNo: 'SLD-01',
      revision: 'Rev. 00001',
      date: '17 AUG 2026',
      engineer: STANDARD_ENGINEERS[0],
      gridAuthority: 'PEA',
      gridVoltage: '220 V',
      gridCableSpec: '2x1C-16 sq.mm. IEC01 In Aerial',
    },
    pvConfig: {
      brand: 'LONGi',
      model: 'LR5-78HGD-650M',
      powerPerPanel: 650,
      panelCount: 8,
      voc: 57.80,
      isc: 14.15,
      vmp: 48.50,
      imp: 13.40,
      totalKwp: 5.20,
    },
    inverterConfig: {
      systemType: 'microinverter',
      brand: 'ATMOCE',
      model: 'ATM-MI-800W (2-in-1)',
      phase: '1P',
      microinverterCount: 4,
      unitPowerKw: 0.800,
      unitPowerVa: 800,
      unitMaxCurrent: 3.48,
      stringInverterCapacityKw: 5,
      stringInverterQuantity: 1,
      stringCount: 1,
      modulesPerString: 8,
      mpptCount: 4,
      totalOutputKw: 3.20,
      totalOutputKva: 3.20,
      hasAntiIslanding: true,
      hasRapidShutdown: true,
    },
    combinerConfig: {
      rcboRating: '20AT 2P',
      rcboType: 'IΔn<30mA ,IC 6kA Type AC',
      mcbRating: 'MCB 2P 20AT,63AF IC 6kA',
      mccbRating: 'MCCB 2P 20AT 63AF',
      acSpdRating: 'AC SPD 2P TYPE II 5/20 KA ~255VAC',
      gatewayModel: 'ATMOCE ECU Gateway & Energy Meter',
      productionCt: 'CTs 200A/40mA',
      consumptionCt: 'CT 200A/40mA',
      phaseCoupler: '',
      hasZeroExport: true,
      hasPhaseCoupler: false,
      cableInverterToCombiner: '1x2C-4 Sq.mm.IEC 60502-1 (CV-FR) / G 6 Sq.mm. IEC01 in PVC 1"',
      cableCombinerToMdb: '2x1C-6 Sq.mm.IEC01 / G6 Sq.mm. IEC01 IN WIREWAY',
      groundRodSpec: '5/8"x10\' COPPER CLAD STEEL GROUND ROD ความต้านทานดินไม่เกิน 5 โอห์ม',
      groundCableSpec: 'G - 10 Sq.mm. IEC 01 (THW)',
    },
    loadCenterConfig: {
      title: 'Consumer Unit',
      mainBreaker: 'RCBO 50AT, 2P IC 10kA IΔn<30mA Type AC',
      solarFeederBreaker: 'MCB 2P 20 AT IC 6kA',
      busbarSpec: 'BUSBAR 100A 100%N & 25% GROUND BUSBAR',
      groundRodSpec: '5/8"x10\' COPPER CLAD STEEL GROUND ROD ความต้านทานดินไม่เกิน 5 โอห์ม',
    },
  },
];
